import 'package:prototype_app/qa/qa_finding.dart';

/// Shared deterministic QA finding fixture for the D.2 test suites.
QaFinding sampleQaFinding({
  String id = 'qa-001',
  String clientId = 'prototype-demo',
  QaSeverity severity = QaSeverity.major,
  String category = 'spacing',
  QaSurface surface = QaSurface.prototype,
  String? screen = 'commerce.home',
  String? story,
  String state = 'default',
  String? direction = 'b',
  String? mixRef,
  String? section = 'home.product-grid',
  QaRegion? region,
  String screenshotRef = 'sha256:capture-1',
  String sourceCommitSha = 'abc123',
  QaRuleSource ruleSource = QaRuleSource.designContract,
  String ruleRef = 'spacing.card.gap',
  String? baselineRef,
  String summary = 'Product-card spacing is inconsistent with the governed token.',
  List<QaEvidence> evidence = const [],
  double? confidence = 0.91,
  DateTime? detectedAt,
}) {
  return QaFinding.detected(
    id: id,
    clientId: clientId,
    severity: severity,
    category: category,
    surface: surface,
    screen: screen,
    story: story,
    state: state,
    direction: direction,
    mixRef: mixRef,
    section: section,
    region: region,
    screenshotRef: screenshotRef,
    sourceCommitSha: sourceCommitSha,
    ruleSource: ruleSource,
    ruleRef: ruleRef,
    baselineRef: baselineRef,
    summary: summary,
    evidence: evidence,
    confidence: confidence,
    actorId: 'visual-qa',
    at: detectedAt ?? DateTime.utc(2026, 9, 17, 10),
  );
}
